### ISSUE TITLE
nvGraphConvertTopology illegal Argument Exception

### ISSUE THREAD

**Issue by aakashkhochare** [jcuda/jnvgraph#1] opened 2017-04-19 09:52 UTC
I am trying to use JCuda to convert a COO topology to CSC. Despite having mapped every step described in http://fareastprogramming.hatenadiary.jp/entry/2016/12/06/203405 , I am getting the following error

Exception in thread "main" java.lang.IllegalArgumentException: Topology data parameter does not have a valid type
	at jcuda.jnvgraph.JNvgraph.nvgraphConvertTopologyNative(Native Method)
	at jcuda.jnvgraph.JNvgraph.nvgraphConvertTopology(JNvgraph.java:305)
	at convertTest.main(convertTest.java:68)

Please advice

**Comment by jcuda** [comment] 2017-04-19 11:35
If you already have this example ported to Java, it would be helpful if you could post it as a minimal example to reproduce the error. 

You may also want to have a look at the PageRank example that is a port of the original NVIDIA CUDA sample to JCuda: https://github.com/jcuda/jcuda-samples/blob/master/JCudaSamples/src/main/java/jcuda/jnvgraph/samples/JNvgraphPageRank.java - maybe this already helps (EDIT: Although it does *not* use the function that causes the error - this was just a general hint)

Otherwise, I'll have to take a closer look at the page that you linked to (with a Google-Translate-JP-to-EN step in between, of course...)

**Comment by aakashkhochare** [comment] 2017-04-19 13:08
Here's the smallest example that can reproduce the error. I am assuming that I have missed some step that has to be performed.
`


	public static void main(String[] args) {
		// TODO Auto-generated method stub
		nvgraphCOOTopology32I COO_input = new nvgraphCOOTopology32I();
		nvgraphCSCTopology32I CSC_output = new nvgraphCSCTopology32I();
		
		/*Set up the values to be copied*/
		float r1 = 1.0f;
		float r2 = 1.0f / 2.0f;
		float r3 = 1.0f / 3.0f;
		int nvertices =  8; 
		int nedges    = 17; 
		int source_indices[] ={  0,  0,  1,  2,  2,  3,  3,  3,  4,  4,  4,  5,  6,  6,  6,  7,  7 }; 
		int destination_indices[] = {  1,  2,  3,  1,  4,  1,  4,  5,  5,  6,  7,  7,  0,  4,  7,  5,  6 };
		float weights[] = { r2, r2, r1, r2, r2, r3, r3, r3, r3, r3, r3, r1, r3, r3, r3, r2, r2 };
		Pointer coo_weights = new Pointer();
		Pointer csc_weights = new Pointer();
		
		/*Set up complete*/
	 	JCuda.setExceptionsEnabled(true);
	 	/*Malloc for the COO and CSC graphs reps*/
		JCuda.cudaMalloc(COO_input.source_indices, nedges*4);
		JCuda.cudaMalloc(COO_input.destination_indices, nedges*4);
		JCuda.cudaMalloc(coo_weights, nedges*4);
		
		JCuda.cudaMalloc(CSC_output.source_indices, nedges*4);
		JCuda.cudaMalloc(CSC_output.destination_offsets, (nvertices+1)*4);
		JCuda.cudaMalloc(csc_weights, nedges*4);

		
		COO_input.nedges = nedges;
		COO_input.nvertices = nvertices;
		COO_input.tag = 1;
		JCuda.cudaMemcpy(COO_input.source_indices,Pointer.to(source_indices), nedges*4, cudaMemcpyKind.cudaMemcpyHostToDevice );
		JCuda.cudaMemcpy(COO_input.destination_indices,Pointer.to(destination_indices), nedges*4,  cudaMemcpyKind.cudaMemcpyHostToDevice);
		JCuda.cudaMemcpy(coo_weights,Pointer.to(weights), nedges*4,  cudaMemcpyKind.cudaMemcpyHostToDevice);		
		nvgraphHandle handle = new nvgraphHandle();
        nvgraphCreate(handle);
        int edge_dimT[] = new int[]{ CUDA_R_32F };        
        JNvgraph.nvgraphConvertTopology(handle, 2, Pointer.to(COO_input), coo_weights,Pointer.to(edge_dimT),1, Pointer.to(CSC_output), csc_weights);
	}

`

**Comment by jcuda** [comment] 2017-04-19 18:13
This is a bug in the implementation of the `nvgraphConvertTopology` method. 

In fact, there are two issues:

1. In the C-version, the method receives the source- and target topology as `void *` pointers. This has been translated to `Pointer` in the Java version, but this is wrong: In the Java version, these parameters will **not** be pointers, but just `Object`s (namely, a `nvgraphCOOTopology32I` Object, for example).

2. The fact that these are not pointers, but Java Objects, caused a second issue: The given Java objects have not properly been updated in the native implementation of this method.

---

Both problems have been fixed now. So now, depending on your preferred workflow and how urgently you need this particular function, there are several options:

- I could provide you an updated JNvgraph JAR file which allows you to call the function. You then still have to manually set the `nvertices` and `nedges` fields in the resulting objects. This is shown in this (exact) version of the new unit test that has been added: https://github.com/jcuda/jnvgraph/blob/a8ea28bfd8d39c0b08660c889aa0f1cb503dbfe2/JNvgraphJava/src/test/java/jcuda/jnvgraph/JNvgraphConvertTopologyTest.java (see the `TODO` near the bottom of the file)

- I could provide an updated JAR, and an updated Windows DLL. You could substitute the latter manually on your system.

- You could manually compile the latest version from the GitHub sources.

- (If it is not urgent: ) You could wait until the next release, which will include this bugfix (although I cannot yet give a precise date for that)

Thanks for bringing this up, and for the example.

**Comment by aakashkhochare** [comment] 2017-04-19 18:24
Actually I am on a fairly tight time schedule, so I'll just pick the first option. Could you please mail the updated JNvgraph JAR to aakashkhochare@gmail.com ?

**Comment by jcuda** [comment] 2017-04-20 01:34
(I occasionally experienced some difficulties when sending JARs to gmail accounts, so...)

I have uploaded the updated JAR to http://jcuda.org/jnvgraph-0.8.0-SNAPSHOT-2017-04-19.jar 

It should work with the original natives (i.e. with the `-natives` JARs of 0.8.0 that contain the DLL/SO files). 

I'll close this issue, because the fix will be part of the next release. 

If you encounter any difficulties with the JAR, just let me know here or via mail.

**Comment by aakashkhochare** [comment] 2017-04-27 21:52
Hey,
The fix for convertTopology did work. However I have a new issue which
could be related to JNI.

When I run nvGraph's SSSP for a large graph, there's a SIGSEGV with the
problematic frame being libjvm.so+0x66fdd1
I will be going through the motions of running gdb, but if possible could
you take a brief look to determine if it's an issue with JNI or not.
The logs are at
https://github.com/aakashkhochare/SwordFFish/tree/master/logs

Sorry for any inconvenience caused.

Regards,
Aakash Khochare

**Comment by jcuda** [comment] 2017-04-28 02:24
This **might**, in fact, also be a bug in JNvgraph- but I'm not sure. 

(If it is a bug: Apologies for that. nvGRAPH has been newly introduced in CUDA 8.0, and there are obviously still some kinks to iron out in JNvgraph...)

Do you have the chance to compile the native library on your OS, so that you could try out a possible fix for this bug? 

--- 

Edit: To be sure: This crash appears **every** time that you start the program - even the original sample from https://github.com/jcuda/jcuda-samples/blob/master/JCudaSamples/src/main/java/jcuda/jnvgraph/samples/JNvgraphSSSP.java - is this correct?

**Comment by aakashkhochare** [comment] 2017-04-28 06:04
I will definitely give it a shot. However I am currently busy with
something else. But I can try debugging on Sunday.

I understand that Nvgraph is a new addition. I would like to help in any
way possible!

**Comment by jcuda** [comment] 2017-04-29 12:06
To be clear: There **is** currently something in the JNI part that has to be changed. (For the involved: There is no global reference created for the `jclass` objects in the initialization). And it is not unlikely that this causes the problem that you're facing. So this **will** be changed anyhow. (Likely on sunday/monday, but I also have some other TODOs right now, so cannot promise the date). 

The actual question is now whether there is any chance that you can try out whether this upcoming change resolves your issue. 

<sub>(BTW: I could try to compile the libs in a Virtual Machine. But that is actually another "TODO", and I'm not sure how long it will take to set everything up, or whether it will work at all...)</sub>

**Comment by aakashkhochare** [comment] 2017-04-29 12:25
I wil definitely try out if the changes are made. Anyway, I am no longer on
a constraint with my project, so I think I can help you with the testing.

**Comment by jcuda** [comment] 2017-05-05 07:15
The changes are now in `jcuda-common` ( https://github.com/jcuda/jcuda-common/commit/7197d7604a5e0f75fab1d3f133dac30e4dae818a ) and `jnvgraph` ( https://github.com/jcuda/jnvgraph/commit/b024af76cf13dd835bd9cbb0a2f455d1f6dfa34d ). This was only a minor fix, so sorry for the long delay. 

Again: It's not entirely clear whether this was the reason for the SIGSEGV that you observed (but it is very likely), so if you could try it out and report whether the issue is resolved now, that would be great.

**Comment by jcuda** [comment] 2017-07-10 21:12
Unless otherwise noted, I assume that this issue is fixed now.

**Closed as completed by jcuda** 2017-07-10 21:12 UTC
